name: Deploy to AWS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # Validate template before deployment
    - name: Validate CloudFormation Template
      run: |
        aws cloudformation validate-template \
          --template-body file://template.yaml

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # Check if stack exists
    - name: Check Stack Status
      id: check-stack
      continue-on-error: true
      run: |
        aws cloudformation describe-stacks \
          --stack-name rpatel-8975566-stack

    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name rpatel-8975566-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset

    - name: Verify Deployment
      run: |
        echo "Verifying stack resources..."
        aws cloudformation list-stack-resources \
          --stack-name rpatel-8975566-stack 