name: Deploy CDK Infrastructure - rpatel8975566

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy AWS Resources
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    
    # Validate template before deployment
    - name: Validate CloudFormation Template
      run: |
        echo "Validating CloudFormation template..."
        aws cloudformation validate-template \
          --template-body file://template.yaml

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    # Check if stack exists
    - name: Check Existing Stack
      id: check-stack
      continue-on-error: true
      run: |
        echo "Checking if stack Rpatel-8975566-stack exists..."
        aws cloudformation describe-stacks \
          --stack-name Rpatel-8975566-stack

    - name: Deploy CloudFormation Stack
      run: |
        echo "Deploying stack Rpatel-8975566-stack..."
        aws cloudformation deploy \
          --template-file template.yaml \
          --stack-name Rpatel-8975566-stack \
          --capabilities CAPABILITY_NAMED_IAM \
          --no-fail-on-empty-changeset \
          --tags Project=rpatel8975566 Owner=rpatel8975566

    - name: Verify Stack Resources
      run: |
        echo "Verifying resources for stack Rpatel-8975566-stack..."
        aws cloudformation list-stack-resources \
          --stack-name Rpatel-8975566-stack 